:8080 {
    @encode_exts {
       path / *.html *.js *.css *.svg
    }
    encode @encode_exts gzip zstd

    handle /config/keycloak-config.json {
        root * /srv
        uri strip_prefix /config

        # enable template processing for files under the root
        templates {
            mime application/json
        }

        # ensure the response Content-Type is application/json for this path
        header Content-Type application/json
        file_server
    }

    handle /* {
        root * /var/www/html/vfeeg-web
        try_files {path} /index.html
        file_server
    }
}